-- =============================================================================
-- SupplyChainOS: End-to-End ETL Pipeline
-- =============================================================================
-- RAW → STAGING → CORE (full load, idempotent, re-runnable)
--
-- Prerequisites:
--   1. Run 01_setup_database.sql   (database, schemas, file format, stage)
--   2. Run 02_create_raw_tables.sql (5 source RAW tables)
--   3. Run 03_create_core_tables.sql (7 CORE tables)
--   4. PUT all 10 CSV files to @SUPPLY_CHAIN_STAGE (source/ and synthetic/)
--
-- This script:
--   Phase 1: COPY INTO RAW tables from staged CSVs
--   Phase 2: Create STAGING tables (type-cast, validated)
--   Phase 3: INSERT OVERWRITE into CORE dimensions
--   Phase 4: INSERT OVERWRITE into CORE facts (incl. PySpark logic)
--   Phase 5: Validate every CORE table
--   Phase 6: Reconciliation report + sample rows
-- =============================================================================

USE DATABASE SUPPLYCHAIN_DB;
USE SCHEMA RAW;


-- #############################################################################
-- PHASE 1: LOAD RAW — COPY INTO from staged CSVs
-- #############################################################################
-- Each COPY uses ON_ERROR='ABORT_STATEMENT' so any parse failure stops the load.
-- FORCE=TRUE allows re-running without needing to re-PUT files.
-- SOURCE_FILE is populated from METADATA$FILENAME for audit lineage.
-- #############################################################################

-- ─── 1a. Create RAW tables for synthetic CSVs (source RAW tables already exist) ─

CREATE TABLE IF NOT EXISTS RAW_SUPPLIER (
    SUPPLIER_ID VARCHAR NOT NULL, SUPPLIER_NAME VARCHAR NOT NULL,
    PRODUCT_ID VARCHAR NOT NULL, PARTS_SUPPLIED VARCHAR NOT NULL,
    REGION VARCHAR NOT NULL, TIER VARCHAR NOT NULL,
    RELIABILITY_SCORE VARCHAR NOT NULL, LEAD_TIME_DAYS VARCHAR NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR,
    CONSTRAINT PK_RAW_SUPPLIER PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE IF NOT EXISTS RAW_CUSTOMER (
    CUSTOMER_ID VARCHAR NOT NULL, CUSTOMER_NAME VARCHAR NOT NULL,
    LOCATION_ID VARCHAR NOT NULL, LOCATION_NAME VARCHAR NOT NULL,
    REGION VARCHAR NOT NULL, SEGMENT VARCHAR NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR,
    CONSTRAINT PK_RAW_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS RAW_ORDER (
    ORDER_ID VARCHAR NOT NULL, SHIPMENT_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL, DESTINATION_LOCATION_ID VARCHAR NOT NULL,
    ORDER_DATE VARCHAR NOT NULL, REQUESTED_DELIVERY_DATE VARCHAR NOT NULL,
    ACTUAL_DELIVERY_DATE VARCHAR NOT NULL, ORDERED_QUANTITY VARCHAR NOT NULL,
    SHIPPED_QUANTITY VARCHAR NOT NULL, PRIORITY VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR,
    CONSTRAINT PK_RAW_ORDER PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS RAW_COST (
    PRODUCT_SHIPMENT_ID VARCHAR NOT NULL, PRODUCT_ID VARCHAR NOT NULL,
    QUANTITY VARCHAR NOT NULL, UNIT_COST VARCHAR NOT NULL,
    MATERIAL_COST VARCHAR NOT NULL, FREIGHT_COST VARCHAR NOT NULL,
    DUTY_RATE VARCHAR NOT NULL, DUTY_COST VARCHAR NOT NULL,
    HANDLING_COST VARCHAR NOT NULL, LANDED_COST VARCHAR NOT NULL,
    DISTANCE_KM VARCHAR NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR,
    CONSTRAINT PK_RAW_COST PRIMARY KEY (PRODUCT_SHIPMENT_ID)
);

CREATE TABLE IF NOT EXISTS RAW_INVENTORY (
    LOCATION_ID VARCHAR NOT NULL, PRODUCT_ID VARCHAR NOT NULL,
    SNAPSHOT_DATE VARCHAR NOT NULL, INVENTORY_QUANTITY VARCHAR NOT NULL,
    DAILY_DEMAND VARCHAR NOT NULL, INBOUND_QUANTITY VARCHAR NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR,
    CONSTRAINT PK_RAW_INVENTORY PRIMARY KEY (LOCATION_ID, PRODUCT_ID, SNAPSHOT_DATE)
);


-- ─── 1b. COPY INTO all 10 RAW tables ────────────────────────────────────────

-- Source files (5)
COPY INTO RAW_SHIPMENT
    (VEHICLE_UNIT_CAPACITY, SHIPMENT_ID, SHIPMENT_NAME, ORIGIN_LOCATION_NAME,
     DESTINATION_LOCATION_NAME, ORIGIN_LOCATION_ID, DESTINATION_LOCATION_ID,
     DEPARTING_ORIGIN_DATE, ARRIVING_DESTINATION_DATE, ORIGIN_LOCATION_GEOHASH,
     DESTINATION_LOCATION_GEOHASH, VEHICLE_ID, VEHICLE_NAME, TOTAL_UNIT_QUANTITY,
     STATUS, SOURCE_FILE)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,
           METADATA$FILENAME
    FROM @SUPPLY_CHAIN_STAGE/source/shipment.csv
)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_PRODUCT_SHIPMENT
    (PRODUCT_SHIPMENT_ID, SHIPMENT_NAME, SHIPMENT_ID, PRODUCT_DESCRIPTION,
     QUANTITY, PRODUCT_ID, DEPARTING_ORIGIN_DATE, ARRIVING_DESTINATION_DATE,
     VEHICLE_NAME, ORIGIN_LOCATION_NAME, ORIGIN_LOCATION_GEOHASH,
     DESTINATION_LOCATION_NAME, DESTINATION_LOCATION_GEOHASH, PRODUCT_SHIPMENT_NAME,
     SOURCE_FILE)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,
           METADATA$FILENAME
    FROM @SUPPLY_CHAIN_STAGE/source/product_shipment.csv
)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_PRODUCT (PRODUCT_ID, PRODUCT_DESCRIPTION, SOURCE_FILE)
FROM (SELECT $1,$2, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/source/product.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_LOCATION (LOCATION_ID, NAME, GEOHASH, SOURCE_FILE)
FROM (SELECT $1,$2,$3, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/source/location.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_VEHICLE (UNIT_CAPACITY, VEHICLE_ID, VEHICLE_NAME, SOURCE_FILE)
FROM (SELECT $1,$2,$3, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/source/vehicle.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

-- Synthetic files (5)
COPY INTO RAW_SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, PRODUCT_ID, PARTS_SUPPLIED, REGION, TIER, RELIABILITY_SCORE, LEAD_TIME_DAYS, SOURCE_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/synthetic/suppliers.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LOCATION_ID, LOCATION_NAME, REGION, SEGMENT, SOURCE_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/synthetic/customers.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_ORDER (ORDER_ID, SHIPMENT_ID, CUSTOMER_ID, DESTINATION_LOCATION_ID, ORDER_DATE, REQUESTED_DELIVERY_DATE, ACTUAL_DELIVERY_DATE, ORDERED_QUANTITY, SHIPPED_QUANTITY, PRIORITY, STATUS, SOURCE_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/synthetic/orders.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_COST (PRODUCT_SHIPMENT_ID, PRODUCT_ID, QUANTITY, UNIT_COST, MATERIAL_COST, FREIGHT_COST, DUTY_RATE, DUTY_COST, HANDLING_COST, LANDED_COST, DISTANCE_KM, SOURCE_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/synthetic/synthetic_costs.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;

COPY INTO RAW_INVENTORY (LOCATION_ID, PRODUCT_ID, SNAPSHOT_DATE, INVENTORY_QUANTITY, DAILY_DEMAND, INBOUND_QUANTITY, SOURCE_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6, METADATA$FILENAME FROM @SUPPLY_CHAIN_STAGE/synthetic/inventory.csv)
ON_ERROR = 'ABORT_STATEMENT' FORCE = TRUE;


-- #############################################################################
-- PHASE 2: STAGING — Type-cast, normalize, validate
-- #############################################################################
-- Every STAGING table:
--   - Casts VARCHAR dates to DATE, numeric strings to NUMBER/FLOAT
--   - Adds _VALID BOOLEAN: FALSE if arrival_date < departure_date
--   - Preserves ALL source rows (invalid rows kept with _VALID=FALSE)
-- #############################################################################

USE SCHEMA STAGING;

-- STG_SHIPMENT: cast dates and quantities, validate arrival >= departure
CREATE OR REPLACE TABLE STG_SHIPMENT AS
SELECT
    SHIPMENT_ID,
    SHIPMENT_NAME,
    ORIGIN_LOCATION_ID,
    ORIGIN_LOCATION_NAME,
    DESTINATION_LOCATION_ID,
    DESTINATION_LOCATION_NAME,
    TRY_TO_DATE(DEPARTING_ORIGIN_DATE)     AS DEPARTURE_DATE,
    TRY_TO_DATE(ARRIVING_DESTINATION_DATE) AS ARRIVAL_DATE,
    ORIGIN_LOCATION_GEOHASH,
    DESTINATION_LOCATION_GEOHASH,
    VEHICLE_ID,
    VEHICLE_NAME,
    TRY_TO_NUMBER(VEHICLE_UNIT_CAPACITY)   AS VEHICLE_CAPACITY,
    TRY_TO_NUMBER(TOTAL_UNIT_QUANTITY)     AS TOTAL_UNIT_QUANTITY,
    STATUS,
    -- Validation: arrival must be on or after departure
    CASE
        WHEN TRY_TO_DATE(ARRIVING_DESTINATION_DATE) >= TRY_TO_DATE(DEPARTING_ORIGIN_DATE)
        THEN TRUE ELSE FALSE
    END AS _VALID,
    LOAD_TIMESTAMP,
    SOURCE_FILE
FROM RAW.RAW_SHIPMENT;

-- STG_PRODUCT_SHIPMENT: cast quantity and dates, validate
CREATE OR REPLACE TABLE STG_PRODUCT_SHIPMENT AS
SELECT
    PRODUCT_SHIPMENT_ID,
    SHIPMENT_ID,
    SHIPMENT_NAME,
    PRODUCT_ID,
    PRODUCT_DESCRIPTION,
    TRY_TO_NUMBER(QUANTITY)                AS QUANTITY,
    TRY_TO_DATE(DEPARTING_ORIGIN_DATE)     AS DEPARTURE_DATE,
    TRY_TO_DATE(ARRIVING_DESTINATION_DATE) AS ARRIVAL_DATE,
    VEHICLE_NAME,
    ORIGIN_LOCATION_NAME,
    ORIGIN_LOCATION_GEOHASH,
    DESTINATION_LOCATION_NAME,
    DESTINATION_LOCATION_GEOHASH,
    PRODUCT_SHIPMENT_NAME,
    CASE
        WHEN TRY_TO_DATE(ARRIVING_DESTINATION_DATE) >= TRY_TO_DATE(DEPARTING_ORIGIN_DATE)
        THEN TRUE ELSE FALSE
    END AS _VALID,
    LOAD_TIMESTAMP,
    SOURCE_FILE
FROM RAW.RAW_PRODUCT_SHIPMENT;

-- STG_PRODUCT: pass-through (no casting needed, already VARCHAR)
CREATE OR REPLACE TABLE STG_PRODUCT AS
SELECT PRODUCT_ID, PRODUCT_DESCRIPTION, TRUE AS _VALID, LOAD_TIMESTAMP, SOURCE_FILE
FROM RAW.RAW_PRODUCT;

-- STG_LOCATION: parse lat/lon from geohash string
CREATE OR REPLACE TABLE STG_LOCATION AS
SELECT
    LOCATION_ID,
    NAME AS LOCATION_NAME,
    GEOHASH,
    TRY_TO_DOUBLE(SPLIT_PART(GEOHASH, ',', 1)) AS LATITUDE,
    TRY_TO_DOUBLE(SPLIT_PART(GEOHASH, ',', 2)) AS LONGITUDE,
    TRUE AS _VALID,
    LOAD_TIMESTAMP,
    SOURCE_FILE
FROM RAW.RAW_LOCATION;

-- STG_VEHICLE: cast capacity to number
CREATE OR REPLACE TABLE STG_VEHICLE AS
SELECT
    VEHICLE_ID, VEHICLE_NAME,
    TRY_TO_NUMBER(UNIT_CAPACITY) AS UNIT_CAPACITY,
    TRUE AS _VALID, LOAD_TIMESTAMP, SOURCE_FILE
FROM RAW.RAW_VEHICLE;

-- STG_SUPPLIER: cast numeric fields
CREATE OR REPLACE TABLE STG_SUPPLIER AS
SELECT
    SUPPLIER_ID, SUPPLIER_NAME, PRODUCT_ID, PARTS_SUPPLIED, REGION, TIER,
    TRY_TO_DOUBLE(RELIABILITY_SCORE) AS RELIABILITY_SCORE,
    TRY_TO_NUMBER(LEAD_TIME_DAYS)    AS LEAD_TIME_DAYS,
    TRUE AS _VALID, LOAD_TIMESTAMP, SOURCE_FILE
FROM RAW.RAW_SUPPLIER;

-- STG_CUSTOMER: pass-through
CREATE OR REPLACE TABLE STG_CUSTOMER AS
SELECT
    CUSTOMER_ID, CUSTOMER_NAME, LOCATION_ID, LOCATION_NAME, REGION, SEGMENT,
    TRUE AS _VALID, LOAD_TIMESTAMP, SOURCE_FILE
FROM RAW.RAW_CUSTOMER;

-- STG_ORDER: cast dates and quantities
CREATE OR REPLACE TABLE STG_ORDER AS
SELECT
    ORDER_ID, SHIPMENT_ID, CUSTOMER_ID, DESTINATION_LOCATION_ID,
    TRY_TO_DATE(ORDER_DATE)               AS ORDER_DATE,
    TRY_TO_DATE(REQUESTED_DELIVERY_DATE)  AS REQUESTED_DELIVERY_DATE,
    TRY_TO_DATE(ACTUAL_DELIVERY_DATE)     AS ACTUAL_DELIVERY_DATE,
    TRY_TO_NUMBER(ORDERED_QUANTITY)       AS ORDERED_QUANTITY,
    TRY_TO_NUMBER(SHIPPED_QUANTITY)       AS SHIPPED_QUANTITY,
    PRIORITY, STATUS,
    CASE WHEN TRY_TO_DATE(ORDER_DATE) IS NOT NULL THEN TRUE ELSE FALSE END AS _VALID,
    LOAD_TIMESTAMP, SOURCE_FILE
FROM RAW.RAW_ORDER;

-- STG_COST: cast all numeric fields
CREATE OR REPLACE TABLE STG_COST AS
SELECT
    PRODUCT_SHIPMENT_ID, PRODUCT_ID,
    TRY_TO_NUMBER(QUANTITY)       AS QUANTITY,
    TRY_TO_DOUBLE(UNIT_COST)     AS UNIT_COST,
    TRY_TO_DOUBLE(MATERIAL_COST) AS MATERIAL_COST,
    TRY_TO_DOUBLE(FREIGHT_COST)  AS FREIGHT_COST,
    TRY_TO_DOUBLE(DUTY_RATE)     AS DUTY_RATE,
    TRY_TO_DOUBLE(DUTY_COST)     AS DUTY_COST,
    TRY_TO_DOUBLE(HANDLING_COST) AS HANDLING_COST,
    TRY_TO_DOUBLE(LANDED_COST)   AS LANDED_COST,
    TRY_TO_DOUBLE(DISTANCE_KM)   AS DISTANCE_KM,
    TRUE AS _VALID, LOAD_TIMESTAMP, SOURCE_FILE
FROM RAW.RAW_COST;

-- STG_INVENTORY: cast date and quantities
CREATE OR REPLACE TABLE STG_INVENTORY AS
SELECT
    LOCATION_ID, PRODUCT_ID,
    TRY_TO_DATE(SNAPSHOT_DATE)         AS SNAPSHOT_DATE,
    TRY_TO_NUMBER(INVENTORY_QUANTITY)  AS INVENTORY_QUANTITY,
    TRY_TO_NUMBER(DAILY_DEMAND)        AS DAILY_DEMAND,
    TRY_TO_NUMBER(INBOUND_QUANTITY)    AS INBOUND_QUANTITY,
    TRUE AS _VALID, LOAD_TIMESTAMP, SOURCE_FILE
FROM RAW.RAW_INVENTORY;


-- #############################################################################
-- PHASE 3: LOAD CORE DIMENSIONS
-- #############################################################################
-- INSERT OVERWRITE = idempotent (full refresh each run).
-- Only _VALID=TRUE rows from STAGING flow into CORE.
-- #############################################################################

USE SCHEMA CORE;

-- DIM_PLANT: from STG_LOCATION (4 rows)
-- Lat/lon parsed in staging from the "lat,lon" geohash string.
INSERT OVERWRITE INTO SUPPLYCHAIN_DB.CORE.DIM_PLANT
    (PLANT_ID, PLANT_NAME, REGION, LATITUDE, LONGITUDE)
SELECT LOCATION_ID, LOCATION_NAME, 'AMERICAS', LATITUDE, LONGITUDE
FROM SUPPLYCHAIN_DB.STAGING.STG_LOCATION
WHERE _VALID = TRUE;

-- DIM_SUPPLIER: from STG_SUPPLIER (6 rows)
INSERT OVERWRITE INTO SUPPLYCHAIN_DB.CORE.DIM_SUPPLIER
    (SUPPLIER_ID, SUPPLIER_NAME, REGION, TIER, RELIABILITY_SCORE, LEAD_TIME_DAYS)
SELECT SUPPLIER_ID, SUPPLIER_NAME, REGION, TIER, RELIABILITY_SCORE, LEAD_TIME_DAYS
FROM SUPPLYCHAIN_DB.STAGING.STG_SUPPLIER
WHERE _VALID = TRUE;

-- DIM_PART: join STG_PRODUCT + STG_COST (unit_cost) + STG_SUPPLIER (primary supplier)
-- Category inferred from second word of product_description (Triangles/Squares/Circles).
-- Primary supplier = Tier 1 for that product.
INSERT OVERWRITE INTO SUPPLYCHAIN_DB.CORE.DIM_PART
    (PART_ID, PART_NAME, CATEGORY, UNIT_COST, SUPPLIER_ID)
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_DESCRIPTION,
    SPLIT_PART(p.PRODUCT_DESCRIPTION, ' ', 2) AS CATEGORY,
    c.UNIT_COST,
    s.SUPPLIER_ID
FROM SUPPLYCHAIN_DB.STAGING.STG_PRODUCT p
JOIN (SELECT DISTINCT PRODUCT_ID, UNIT_COST FROM SUPPLYCHAIN_DB.STAGING.STG_COST) c
    ON p.PRODUCT_ID = c.PRODUCT_ID
JOIN SUPPLYCHAIN_DB.STAGING.STG_SUPPLIER s
    ON p.PRODUCT_ID = s.PRODUCT_ID AND s.TIER = 'Tier 1';

-- DIM_CUSTOMER: from STG_CUSTOMER (8 rows)
-- LOCATION_ID maps to PLANT_ID (same values, different domain name).
INSERT OVERWRITE INTO SUPPLYCHAIN_DB.CORE.DIM_CUSTOMER
    (CUSTOMER_ID, CUSTOMER_NAME, REGION, SEGMENT, PLANT_ID)
SELECT CUSTOMER_ID, CUSTOMER_NAME, REGION, SEGMENT, LOCATION_ID
FROM SUPPLYCHAIN_DB.STAGING.STG_CUSTOMER
WHERE _VALID = TRUE;


-- #############################################################################
-- PHASE 4: LOAD CORE FACTS
-- #############################################################################

-- FACT_ORDER: from STG_ORDER (83 rows)
-- PART_ID = the product with highest quantity in the linked shipment
-- (one shipment can carry 1–3 products; we pick the dominant one).
INSERT OVERWRITE INTO SUPPLYCHAIN_DB.CORE.FACT_ORDER
    (ORDER_ID, CUSTOMER_ID, PLANT_ID, PART_ID, ORDER_DATE,
     REQUESTED_DELIVERY_DATE, ORDERED_QUANTITY, PRIORITY, STATUS)
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.DESTINATION_LOCATION_ID AS PLANT_ID,
    ps.PRODUCT_ID             AS PART_ID,
    o.ORDER_DATE,
    o.REQUESTED_DELIVERY_DATE,
    o.ORDERED_QUANTITY,
    o.PRIORITY,
    o.STATUS
FROM SUPPLYCHAIN_DB.STAGING.STG_ORDER o
JOIN (
    -- Pick dominant product per shipment (highest quantity)
    SELECT SHIPMENT_ID, PRODUCT_ID,
           ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY QUANTITY DESC) AS RN
    FROM SUPPLYCHAIN_DB.STAGING.STG_PRODUCT_SHIPMENT
    WHERE _VALID = TRUE
) ps ON o.SHIPMENT_ID = ps.SHIPMENT_ID AND ps.RN = 1
WHERE o._VALID = TRUE;


-- FACT_INVENTORY: from STG_INVENTORY (360 rows)
INSERT OVERWRITE INTO SUPPLYCHAIN_DB.CORE.FACT_INVENTORY
    (PLANT_ID, PART_ID, SNAPSHOT_DATE, INVENTORY_QUANTITY, DAILY_DEMAND, INBOUND_QUANTITY)
SELECT LOCATION_ID, PRODUCT_ID, SNAPSHOT_DATE, INVENTORY_QUANTITY, DAILY_DEMAND, INBOUND_QUANTITY
FROM SUPPLYCHAIN_DB.STAGING.STG_INVENTORY
WHERE _VALID = TRUE;


-- FACT_SHIPMENT: the most complex load — 4-way join + PySpark-derived columns
-- Grain: 1 row per shipment × part (159 rows from product_shipment).
--
-- Join chain:
--   STG_PRODUCT_SHIPMENT  (grain: 159 rows, the product line items)
--   + STG_SHIPMENT         (route, vehicle, dates — joined on shipment_id)
--   + STG_ORDER            (order linkage + requested_delivery_date — joined on shipment_id)
--   + STG_COST             (cost measures — joined on product_shipment_id)
--
-- PySpark transformation logic (from src/transformation.py) preserved exactly:
--   Step 1: delivery_days = DATEDIFF('day', departure_date, arrival_date)
--   Step 2: is_valid_shipment = delivery_days >= 0
--   Step 3: avg_route_delivery_days = AVG(delivery_days) OVER (PARTITION BY origin, dest)
--   Step 4: risk_flag = High if > avg+3, Medium if > avg, else Low
--   Step 5: decision = Investigate / Monitor / Normal

INSERT OVERWRITE INTO SUPPLYCHAIN_DB.CORE.FACT_SHIPMENT (
    SHIPMENT_LINE_ID, SHIPMENT_ID, ORDER_ID, PART_ID,
    ORIGIN_PLANT_ID, DESTINATION_PLANT_ID, VEHICLE_ID,
    DEPARTURE_DATE, ARRIVAL_DATE, REQUESTED_DELIVERY_DATE,
    SHIPPED_QUANTITY, VEHICLE_CAPACITY,
    UNIT_COST, MATERIAL_COST, FREIGHT_COST, DUTY_COST,
    HANDLING_COST, LANDED_COST, DISTANCE_KM,
    DELIVERY_DAYS, IS_VALID_SHIPMENT, AVG_ROUTE_DELIVERY_DAYS,
    RISK_FLAG, DECISION
)
WITH shipment_base AS (
    -- CTE 1: Join product_shipment lines with parent shipment for route info
    SELECT
        ps.PRODUCT_SHIPMENT_ID    AS SHIPMENT_LINE_ID,
        ps.SHIPMENT_ID,
        ps.PRODUCT_ID             AS PART_ID,
        s.ORIGIN_LOCATION_ID      AS ORIGIN_PLANT_ID,
        s.DESTINATION_LOCATION_ID AS DESTINATION_PLANT_ID,
        s.VEHICLE_ID,
        s.DEPARTURE_DATE,
        s.ARRIVAL_DATE,
        s.VEHICLE_CAPACITY,
        ps.QUANTITY               AS SHIPPED_QUANTITY,
        s.ORIGIN_LOCATION_NAME,
        s.DESTINATION_LOCATION_NAME
    FROM SUPPLYCHAIN_DB.STAGING.STG_PRODUCT_SHIPMENT ps
    JOIN SUPPLYCHAIN_DB.STAGING.STG_SHIPMENT s
        ON ps.SHIPMENT_ID = s.SHIPMENT_ID
    WHERE ps._VALID = TRUE AND s._VALID = TRUE
),
with_order AS (
    -- CTE 2: Attach order_id and requested_delivery_date via shipment_id
    SELECT
        sb.*,
        o.ORDER_ID,
        o.REQUESTED_DELIVERY_DATE
    FROM shipment_base sb
    JOIN SUPPLYCHAIN_DB.STAGING.STG_ORDER o
        ON sb.SHIPMENT_ID = o.SHIPMENT_ID
),
with_costs AS (
    -- CTE 3: Attach cost measures + compute delivery_days and is_valid
    SELECT
        wo.*,
        c.UNIT_COST,
        c.MATERIAL_COST,
        c.FREIGHT_COST,
        c.DUTY_COST,
        c.HANDLING_COST,
        c.LANDED_COST,
        c.DISTANCE_KM,
        -- PySpark Step 1: delivery_days
        DATEDIFF('day', wo.DEPARTURE_DATE, wo.ARRIVAL_DATE)        AS DELIVERY_DAYS,
        -- PySpark Step 2: is_valid_shipment
        DATEDIFF('day', wo.DEPARTURE_DATE, wo.ARRIVAL_DATE) >= 0   AS IS_VALID_SHIPMENT
    FROM with_order wo
    JOIN SUPPLYCHAIN_DB.STAGING.STG_COST c
        ON wo.SHIPMENT_LINE_ID = c.PRODUCT_SHIPMENT_ID
),
with_route_avg AS (
    -- CTE 4: PySpark Step 3 — route-level average delivery days
    -- Window partition matches PySpark exactly: (origin_location_name, destination_location_name)
    SELECT
        wc.*,
        AVG(DELIVERY_DAYS) OVER (
            PARTITION BY ORIGIN_LOCATION_NAME, DESTINATION_LOCATION_NAME
        ) AS AVG_ROUTE_DELIVERY_DAYS
    FROM with_costs wc
)
-- Final SELECT: PySpark Steps 4+5 — risk_flag and decision
SELECT
    SHIPMENT_LINE_ID, SHIPMENT_ID, ORDER_ID, PART_ID,
    ORIGIN_PLANT_ID, DESTINATION_PLANT_ID, VEHICLE_ID,
    DEPARTURE_DATE, ARRIVAL_DATE, REQUESTED_DELIVERY_DATE,
    SHIPPED_QUANTITY, VEHICLE_CAPACITY,
    UNIT_COST, MATERIAL_COST, FREIGHT_COST, DUTY_COST, HANDLING_COST, LANDED_COST, DISTANCE_KM,
    DELIVERY_DAYS,
    IS_VALID_SHIPMENT,
    AVG_ROUTE_DELIVERY_DAYS,
    -- PySpark Step 4: risk_flag (evaluated top-down, same order as CASE WHEN)
    CASE
        WHEN DELIVERY_DAYS > AVG_ROUTE_DELIVERY_DAYS + 3 THEN 'High'
        WHEN DELIVERY_DAYS > AVG_ROUTE_DELIVERY_DAYS     THEN 'Medium'
        ELSE 'Low'
    END AS RISK_FLAG,
    -- PySpark Step 5: decision mapping
    CASE
        WHEN DELIVERY_DAYS > AVG_ROUTE_DELIVERY_DAYS + 3 THEN 'Investigate'
        WHEN DELIVERY_DAYS > AVG_ROUTE_DELIVERY_DAYS     THEN 'Monitor'
        ELSE 'Normal'
    END AS DECISION
FROM with_route_avg;


-- #############################################################################
-- PHASE 5: VALIDATION
-- #############################################################################

-- ─── 5a. Row count reconciliation: RAW → STAGING → CORE ─────────────────────
SELECT '--- RECONCILIATION REPORT ---' AS REPORT;

SELECT
    'RAW_SHIPMENT'    AS SOURCE_TABLE, COUNT(*) AS RAW_ROWS, 83  AS EXPECTED FROM RAW.RAW_SHIPMENT
UNION ALL SELECT
    'RAW_PRODUCT_SHIPMENT', COUNT(*), 159 FROM RAW.RAW_PRODUCT_SHIPMENT
UNION ALL SELECT
    'RAW_PRODUCT',    COUNT(*), 3   FROM RAW.RAW_PRODUCT
UNION ALL SELECT
    'RAW_LOCATION',   COUNT(*), 4   FROM RAW.RAW_LOCATION
UNION ALL SELECT
    'RAW_VEHICLE',    COUNT(*), 83  FROM RAW.RAW_VEHICLE
UNION ALL SELECT
    'RAW_SUPPLIER',   COUNT(*), 6   FROM RAW.RAW_SUPPLIER
UNION ALL SELECT
    'RAW_CUSTOMER',   COUNT(*), 8   FROM RAW.RAW_CUSTOMER
UNION ALL SELECT
    'RAW_ORDER',      COUNT(*), 83  FROM RAW.RAW_ORDER
UNION ALL SELECT
    'RAW_COST',       COUNT(*), 159 FROM RAW.RAW_COST
UNION ALL SELECT
    'RAW_INVENTORY',  COUNT(*), 360 FROM RAW.RAW_INVENTORY
ORDER BY 1;


-- ─── 5b. Primary key uniqueness ─────────────────────────────────────────────
SELECT '--- PK UNIQUENESS ---' AS REPORT;

SELECT 'DIM_SUPPLIER'   AS TBL, COUNT(*) AS ROW_CNT, COUNT(DISTINCT SUPPLIER_ID) AS DISTINCT_PK,
       CASE WHEN COUNT(*) = COUNT(DISTINCT SUPPLIER_ID) THEN 'PASS' ELSE 'FAIL' END AS PK_CHECK
FROM CORE.DIM_SUPPLIER
UNION ALL SELECT 'DIM_PART', COUNT(*), COUNT(DISTINCT PART_ID),
       CASE WHEN COUNT(*) = COUNT(DISTINCT PART_ID) THEN 'PASS' ELSE 'FAIL' END
FROM CORE.DIM_PART
UNION ALL SELECT 'DIM_PLANT', COUNT(*), COUNT(DISTINCT PLANT_ID),
       CASE WHEN COUNT(*) = COUNT(DISTINCT PLANT_ID) THEN 'PASS' ELSE 'FAIL' END
FROM CORE.DIM_PLANT
UNION ALL SELECT 'DIM_CUSTOMER', COUNT(*), COUNT(DISTINCT CUSTOMER_ID),
       CASE WHEN COUNT(*) = COUNT(DISTINCT CUSTOMER_ID) THEN 'PASS' ELSE 'FAIL' END
FROM CORE.DIM_CUSTOMER
UNION ALL SELECT 'FACT_ORDER', COUNT(*), COUNT(DISTINCT ORDER_ID),
       CASE WHEN COUNT(*) = COUNT(DISTINCT ORDER_ID) THEN 'PASS' ELSE 'FAIL' END
FROM CORE.FACT_ORDER
UNION ALL SELECT 'FACT_SHIPMENT', COUNT(*), COUNT(DISTINCT SHIPMENT_LINE_ID),
       CASE WHEN COUNT(*) = COUNT(DISTINCT SHIPMENT_LINE_ID) THEN 'PASS' ELSE 'FAIL' END
FROM CORE.FACT_SHIPMENT
UNION ALL SELECT 'FACT_INVENTORY', COUNT(*), COUNT(DISTINCT PLANT_ID||PART_ID||SNAPSHOT_DATE),
       CASE WHEN COUNT(*) = COUNT(DISTINCT PLANT_ID||PART_ID||SNAPSHOT_DATE) THEN 'PASS' ELSE 'FAIL' END
FROM CORE.FACT_INVENTORY
ORDER BY 1;


-- ─── 5c. Foreign key coverage (zero orphans expected) ────────────────────────
SELECT '--- FK COVERAGE ---' AS REPORT;

SELECT 'ORDER→CUSTOMER'    AS FK, COUNT(*) AS ORPHANS FROM CORE.FACT_ORDER fo LEFT JOIN CORE.DIM_CUSTOMER  dc ON fo.CUSTOMER_ID = dc.CUSTOMER_ID WHERE dc.CUSTOMER_ID IS NULL
UNION ALL SELECT 'ORDER→PLANT',    COUNT(*) FROM CORE.FACT_ORDER fo LEFT JOIN CORE.DIM_PLANT dp ON fo.PLANT_ID = dp.PLANT_ID WHERE dp.PLANT_ID IS NULL
UNION ALL SELECT 'ORDER→PART',     COUNT(*) FROM CORE.FACT_ORDER fo LEFT JOIN CORE.DIM_PART  dp ON fo.PART_ID  = dp.PART_ID  WHERE dp.PART_ID IS NULL
UNION ALL SELECT 'SHIP→ORDER',     COUNT(*) FROM CORE.FACT_SHIPMENT fs LEFT JOIN CORE.FACT_ORDER  fo ON fs.ORDER_ID = fo.ORDER_ID WHERE fo.ORDER_ID IS NULL
UNION ALL SELECT 'SHIP→PART',      COUNT(*) FROM CORE.FACT_SHIPMENT fs LEFT JOIN CORE.DIM_PART    dp ON fs.PART_ID  = dp.PART_ID  WHERE dp.PART_ID IS NULL
UNION ALL SELECT 'SHIP→ORIGIN',    COUNT(*) FROM CORE.FACT_SHIPMENT fs LEFT JOIN CORE.DIM_PLANT   dp ON fs.ORIGIN_PLANT_ID = dp.PLANT_ID WHERE dp.PLANT_ID IS NULL
UNION ALL SELECT 'SHIP→DEST',      COUNT(*) FROM CORE.FACT_SHIPMENT fs LEFT JOIN CORE.DIM_PLANT   dp ON fs.DESTINATION_PLANT_ID = dp.PLANT_ID WHERE dp.PLANT_ID IS NULL
UNION ALL SELECT 'INV→PLANT',      COUNT(*) FROM CORE.FACT_INVENTORY fi LEFT JOIN CORE.DIM_PLANT   dp ON fi.PLANT_ID = dp.PLANT_ID WHERE dp.PLANT_ID IS NULL
UNION ALL SELECT 'INV→PART',       COUNT(*) FROM CORE.FACT_INVENTORY fi LEFT JOIN CORE.DIM_PART    dp ON fi.PART_ID  = dp.PART_ID  WHERE dp.PART_ID IS NULL
UNION ALL SELECT 'PART→SUPPLIER',  COUNT(*) FROM CORE.DIM_PART dp LEFT JOIN CORE.DIM_SUPPLIER ds ON dp.SUPPLIER_ID = ds.SUPPLIER_ID WHERE ds.SUPPLIER_ID IS NULL
UNION ALL SELECT 'CUST→PLANT',     COUNT(*) FROM CORE.DIM_CUSTOMER dc LEFT JOIN CORE.DIM_PLANT dp ON dc.PLANT_ID = dp.PLANT_ID WHERE dp.PLANT_ID IS NULL
ORDER BY 1;


-- ─── 5d. Data quality: risk_flag distribution ────────────────────────────────
SELECT '--- RISK FLAG DISTRIBUTION ---' AS REPORT;

SELECT RISK_FLAG, DECISION, COUNT(*) AS CNT
FROM CORE.FACT_SHIPMENT
GROUP BY RISK_FLAG, DECISION
ORDER BY RISK_FLAG;


-- ─── 5e. Sample rows ────────────────────────────────────────────────────────
SELECT '--- SAMPLE: DIM_SUPPLIER ---' AS REPORT;
SELECT * FROM CORE.DIM_SUPPLIER LIMIT 3;

SELECT '--- SAMPLE: DIM_PART ---' AS REPORT;
SELECT * FROM CORE.DIM_PART;

SELECT '--- SAMPLE: DIM_PLANT ---' AS REPORT;
SELECT * FROM CORE.DIM_PLANT;

SELECT '--- SAMPLE: DIM_CUSTOMER ---' AS REPORT;
SELECT * FROM CORE.DIM_CUSTOMER LIMIT 3;

SELECT '--- SAMPLE: FACT_ORDER ---' AS REPORT;
SELECT * FROM CORE.FACT_ORDER LIMIT 3;

SELECT '--- SAMPLE: FACT_SHIPMENT (High Risk) ---' AS REPORT;
SELECT SHIPMENT_LINE_ID, PART_ID, DELIVERY_DAYS, AVG_ROUTE_DELIVERY_DAYS,
       RISK_FLAG, DECISION, LANDED_COST
FROM CORE.FACT_SHIPMENT WHERE RISK_FLAG = 'High' LIMIT 3;

SELECT '--- SAMPLE: FACT_INVENTORY ---' AS REPORT;
SELECT * FROM CORE.FACT_INVENTORY LIMIT 3;

-- =============================================================================
-- ETL COMPLETE
-- =============================================================================
